pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('java-maven-demo') {
                    bat 'mvn -B clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('java-maven-demo') {
                    bat 'mvn -B test'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                // Path is relative to the workspace; reports are inside the module
                junit 'java-maven-demo/target/surefire-reports/*.xml'
            }
        }
    }
}